spring:
  application:
    name: video-uploader
  data:
    mongodb:
      #uri: mongodb://localhost:27017/videos_uploader
      host: localhost
      database: videos
      authentication-database: admin
      username: root
      password: rootpassword
      auto-index-creation: true
      port: 27017


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      # Optional: define default exchange and routing key for template if needed
      exchange: video-converted-exchange
      routing-key: video.converted
    listener:
      simple:
        acknowledge-mode: auto

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.mongodb.reactivestreams.client: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.connection: DEBUG


app:
  rabbit:
    exchange:
      upload: video-exchange
      convert: video-converted-exchange
    queues:
      upload: video-uploaded-queue
      convert: video-converted-queue
    routingKeys:
      upload: video.uploaded
      convert: video.converted
  storage:
    type: local           # "local" or "s3"
    local:
      base-dir: microservices/--dev--/storage
    s3:
      bucket: my-bucket
      region: eu-west-1
  ffmpeg:
    path: microservices/--dev--/codecs/ffmpeg-7.1.1/ffprobe.exe      # relative to project root (or /opt/app in Docker)
